### ISSUE TITLE
"Sign in with" returns an error

### ISSUE THREAD

**Issue by curran** [backand/simple-noterious-app#3]
When clicking any of the three buttons under "Sign in with", regardless of whether "new user" is checked or not, the following error is displayed:

```
<Error>
   <Message>Blob is not ready yet.</Message>
</Error>
```

This occurs on the app instance hosted at http://noterious.backand.net/#/login

**Comment by netrc** [comment]
Had the same problem - You need to set Backand.setAppName('yourApp');
